### PR TITLE
correct name of make-branch

### PR DESCRIPTION
**Pull request by thijstriemstra**
Correct 2 more make-branch references for ticket #1.

### CODE REVIEW

**Comment by adiroiban** [comment]
I have not saw this ticket and created #7 ... why on earth does it take years to land such an annoying bug? :disappointed:

**Comment by thijstriemstra** [comment]
I decided to stop contributing because of that, youre totally right

**Comment by glyph** [comment]
> I have not saw this ticket and created #7 ... why on earth does it take years to land such an annoying bug? :disappointed: 

One reason might be that when people notice bugs, they just file new bugs and PRs and don't bother to look at the existing ones :).

**Comment by glyph** [comment]
@thijstriemstra - you raise a good point though, and I think the cause is that basically nobody has write access to this repository.  I'll add you and @adiroiban if you still have any interest in contributing.  @tomprince - I also notice that you seem to be the only person cleared to release this project on PyPI - can you hand out the keys to a few more folks?  Thanks!

**Pull request merged**
